# Random Sampling with NumPy

In [2]:
import numpy as np
import random

In [3]:
np.random.random(1)

array([0.18612989])

In [4]:
np.random.random((3,3))

array([[0.82967736, 0.57143633, 0.31168895],
       [0.7571519 , 0.08928255, 0.93745044],
       [0.97446186, 0.50685856, 0.47740188]])

In [5]:
np.random.randint(1,4)

3

In [6]:
np.random.randint(1,4,(4,4))

array([[3, 1, 1, 1],
       [3, 3, 2, 2],
       [3, 3, 2, 1],
       [2, 3, 2, 1]])

In [7]:
np.random.randint(1,4,(2,4,4))

array([[[1, 2, 2, 3],
        [1, 1, 1, 1],
        [2, 3, 3, 3],
        [2, 1, 1, 2]],

       [[1, 2, 3, 3],
        [2, 3, 1, 3],
        [1, 3, 2, 1],
        [2, 3, 2, 2]]])

In [9]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [13]:
np.random.seed(0)
np.random.randint(1,4,(2,4,4))

array([[[1, 2, 1, 2],
        [2, 3, 1, 3],
        [1, 1, 1, 3],
        [2, 3, 3, 1]],

       [[2, 2, 2, 2],
        [1, 2, 1, 1],
        [2, 3, 1, 3],
        [1, 2, 2, 3]]])

In [14]:
np.random.rand(3)

array([0.72063265, 0.58201979, 0.53737323])

In [16]:
np.random.rand(3,3)

array([[0.18633234, 0.73691818, 0.21655035],
       [0.13521817, 0.32414101, 0.14967487],
       [0.22232139, 0.38648898, 0.90259848]])

In [17]:
np.random.randn(3,3)

array([[ 2.16171737, -0.95693143,  0.06731083],
       [ 0.20649884, -0.45688133, -1.05997576],
       [ 0.61495732,  1.42966077, -0.21195226]])

In [18]:
x=[1,2,3,4,5]
np.random.choice(x)

4

In [19]:
x=[1,2,3,4,5]
np.random.choice(x)

5

In [20]:
x

[1, 2, 3, 4, 5]

In [21]:
np.random.permutation(x)

array([3, 2, 1, 4, 5])

In [22]:
np.random.permutation(x)

array([2, 3, 4, 1, 5])