# NumPy Functions:

In [1]:
import numpy as np

# arange()

In [3]:
# np.arrange(start,end,steps)
arr_1d=np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
even_arr=np.arange(0,13,2)
print(even_arr)

[ 0  2  4  6  8 10 12]


# linspace()

In [8]:
np.linspace(1,6,3)

array([1. , 3.5, 6. ])

# reshape()

In [14]:
# arr_2d=arr_1d.reshape(row,column)
arr_2d=arr_1d.reshape(3,4)
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
arr_3d = arr_1d.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [17]:
arr=np.arange(1,13).reshape(2,6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel()

In [18]:
# converst multi dimesional array into 1-d array

arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten

In [19]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [20]:
arr.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])